CREATE TABLE IF NOT EXISTS sync_run (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dataset VARCHAR(64) NOT NULL,
  mode VARCHAR(32) NOT NULL,
  start_date CHAR(8) NULL,
  end_date CHAR(8) NULL,
  status VARCHAR(32) NOT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  fetched_rows BIGINT NOT NULL DEFAULT 0,
  affected_rows BIGINT NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  KEY idx_sync_run_dataset_started (dataset, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS trade_cal (
  exchange VARCHAR(16) NOT NULL,
  cal_date CHAR(8) NOT NULL,
  is_open TINYINT NOT NULL,
  pretrade_date CHAR(8) NULL,
  PRIMARY KEY (exchange, cal_date),
  KEY idx_trade_cal_open_date (is_open, cal_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_basic (
  ts_code VARCHAR(16) NOT NULL PRIMARY KEY,
  symbol VARCHAR(16) NULL,
  name VARCHAR(64) NULL,
  area VARCHAR(64) NULL,
  industry VARCHAR(64) NULL,
  fullname VARCHAR(128) NULL,
  enname VARCHAR(256) NULL,
  cnspell VARCHAR(64) NULL,
  market VARCHAR(32) NULL,
  exchange VARCHAR(16) NULL,
  curr_type VARCHAR(16) NULL,
  list_status VARCHAR(8) NULL,
  list_date CHAR(8) NULL,
  delist_date CHAR(8) NULL,
  is_hs VARCHAR(8) NULL,
  KEY idx_stock_basic_list_status (list_status),
  KEY idx_stock_basic_exchange (exchange)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_daily (
  ts_code VARCHAR(16) NOT NULL,
  trade_date CHAR(8) NOT NULL,
  open DECIMAL(18,4) NULL,
  high DECIMAL(18,4) NULL,
  low DECIMAL(18,4) NULL,
  close DECIMAL(18,4) NULL,
  pre_close DECIMAL(18,4) NULL,
  `change` DECIMAL(18,4) NULL,
  pct_chg DECIMAL(18,6) NULL,
  vol DECIMAL(24,4) NULL,
  amount DECIMAL(24,4) NULL,
  PRIMARY KEY (ts_code, trade_date),
  KEY idx_stock_daily_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_daily_basic (
  ts_code VARCHAR(16) NOT NULL,
  trade_date CHAR(8) NOT NULL,
  close DECIMAL(18,4) NULL,
  turnover_rate DECIMAL(18,6) NULL,
  turnover_rate_f DECIMAL(18,6) NULL,
  volume_ratio DECIMAL(18,6) NULL,
  pe DECIMAL(18,6) NULL,
  pe_ttm DECIMAL(18,6) NULL,
  pb DECIMAL(18,6) NULL,
  ps DECIMAL(18,6) NULL,
  ps_ttm DECIMAL(18,6) NULL,
  dv_ratio DECIMAL(18,6) NULL,
  dv_ttm DECIMAL(18,6) NULL,
  total_share DECIMAL(24,6) NULL,
  float_share DECIMAL(24,6) NULL,
  free_share DECIMAL(24,6) NULL,
  total_mv DECIMAL(24,6) NULL,
  circ_mv DECIMAL(24,6) NULL,
  PRIMARY KEY (ts_code, trade_date),
  KEY idx_stock_daily_basic_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_adj_factor (
  ts_code VARCHAR(16) NOT NULL,
  trade_date CHAR(8) NOT NULL,
  adj_factor DECIMAL(24,8) NULL,
  PRIMARY KEY (ts_code, trade_date),
  KEY idx_stock_adj_factor_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS index_basic (
  ts_code VARCHAR(16) NOT NULL PRIMARY KEY,
  name VARCHAR(128) NULL,
  fullname VARCHAR(256) NULL,
  market VARCHAR(32) NULL,
  publisher VARCHAR(128) NULL,
  index_type VARCHAR(64) NULL,
  category VARCHAR(64) NULL,
  base_date CHAR(8) NULL,
  base_point DECIMAL(18,4) NULL,
  list_date CHAR(8) NULL,
  weight_rule TEXT NULL,
  `desc` TEXT NULL,
  exp_date CHAR(8) NULL,
  KEY idx_index_basic_market (market)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS index_daily (
  ts_code VARCHAR(16) NOT NULL,
  trade_date CHAR(8) NOT NULL,
  close DECIMAL(18,4) NULL,
  open DECIMAL(18,4) NULL,
  high DECIMAL(18,4) NULL,
  low DECIMAL(18,4) NULL,
  pre_close DECIMAL(18,4) NULL,
  `change` DECIMAL(18,4) NULL,
  pct_chg DECIMAL(18,6) NULL,
  vol DECIMAL(24,4) NULL,
  amount DECIMAL(24,4) NULL,
  PRIMARY KEY (ts_code, trade_date),
  KEY idx_index_daily_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS index_daily_basic (
  ts_code VARCHAR(16) NOT NULL,
  trade_date CHAR(8) NOT NULL,
  total_mv DECIMAL(24,6) NULL,
  float_mv DECIMAL(24,6) NULL,
  total_share DECIMAL(24,6) NULL,
  float_share DECIMAL(24,6) NULL,
  free_share DECIMAL(24,6) NULL,
  turnover_rate DECIMAL(18,6) NULL,
  turnover_rate_f DECIMAL(18,6) NULL,
  pe DECIMAL(18,6) NULL,
  pe_ttm DECIMAL(18,6) NULL,
  pb DECIMAL(18,6) NULL,
  PRIMARY KEY (ts_code, trade_date),
  KEY idx_index_daily_basic_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_moneyflow_ths (
  ts_code VARCHAR(16) NOT NULL,
  trade_date CHAR(8) NOT NULL,
  name VARCHAR(64) NULL,
  pct_change DECIMAL(18,6) NULL,
  latest DECIMAL(18,4) NULL,
  net_amount DECIMAL(24,6) NULL,
  net_d5_amount DECIMAL(24,6) NULL,
  buy_lg_amount DECIMAL(24,6) NULL,
  buy_lg_amount_rate DECIMAL(18,6) NULL,
  sell_lg_amount DECIMAL(24,6) NULL,
  sell_lg_amount_rate DECIMAL(18,6) NULL,
  buy_md_amount DECIMAL(24,6) NULL,
  buy_md_amount_rate DECIMAL(18,6) NULL,
  sell_md_amount DECIMAL(24,6) NULL,
  sell_md_amount_rate DECIMAL(18,6) NULL,
  buy_sm_amount DECIMAL(24,6) NULL,
  buy_sm_amount_rate DECIMAL(18,6) NULL,
  sell_sm_amount DECIMAL(24,6) NULL,
  sell_sm_amount_rate DECIMAL(18,6) NULL,
  PRIMARY KEY (ts_code, trade_date),
  KEY idx_stock_moneyflow_ths_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS kpl_concept_cons (
  ts_code VARCHAR(16) NOT NULL,
  con_code VARCHAR(32) NOT NULL,
  trade_date CHAR(8) NOT NULL,
  name VARCHAR(64) NULL,
  con_name VARCHAR(128) NULL,
  hot_num INT NULL,
  PRIMARY KEY (ts_code, con_code, trade_date),
  KEY idx_kpl_concept_cons_trade_date (trade_date),
  KEY idx_kpl_concept_cons_con_code (con_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fina_indicator (
  ts_code VARCHAR(16) NOT NULL,
  ann_date CHAR(8) NOT NULL,
  end_date CHAR(8) NOT NULL,
  eps DECIMAL(24,8) NULL,
  dt_eps DECIMAL(24,8) NULL,
  total_revenue_ps DECIMAL(24,8) NULL,
  revenue_ps DECIMAL(24,8) NULL,
  capital_rese_ps DECIMAL(24,8) NULL,
  surplus_rese_ps DECIMAL(24,8) NULL,
  undist_profit_ps DECIMAL(24,8) NULL,
  extra_item DECIMAL(24,8) NULL,
  profit_dedt DECIMAL(24,8) NULL,
  gross_margin DECIMAL(24,8) NULL,
  current_ratio DECIMAL(24,8) NULL,
  quick_ratio DECIMAL(24,8) NULL,
  cash_ratio DECIMAL(24,8) NULL,
  ar_turn DECIMAL(24,8) NULL,
  ca_turn DECIMAL(24,8) NULL,
  fa_turn DECIMAL(24,8) NULL,
  assets_turn DECIMAL(24,8) NULL,
  op_income DECIMAL(24,8) NULL,
  valuechange_income DECIMAL(24,8) NULL,
  interst_income DECIMAL(24,8) NULL,
  daa DECIMAL(24,8) NULL,
  ebit DECIMAL(24,8) NULL,
  ebitda DECIMAL(24,8) NULL,
  fcff DECIMAL(24,8) NULL,
  fcfe DECIMAL(24,8) NULL,
  current_exint DECIMAL(24,8) NULL,
  noncurrent_exint DECIMAL(24,8) NULL,
  interestdebt DECIMAL(24,8) NULL,
  netdebt DECIMAL(24,8) NULL,
  tangible_asset DECIMAL(24,8) NULL,
  working_capital DECIMAL(24,8) NULL,
  networking_capital DECIMAL(24,8) NULL,
  invest_capital DECIMAL(24,8) NULL,
  retained_earnings DECIMAL(24,8) NULL,
  diluted2_eps DECIMAL(24,8) NULL,
  bps DECIMAL(24,8) NULL,
  ocfps DECIMAL(24,8) NULL,
  retainedps DECIMAL(24,8) NULL,
  cfps DECIMAL(24,8) NULL,
  ebit_ps DECIMAL(24,8) NULL,
  fcff_ps DECIMAL(24,8) NULL,
  fcfe_ps DECIMAL(24,8) NULL,
  netprofit_margin DECIMAL(24,8) NULL,
  grossprofit_margin DECIMAL(24,8) NULL,
  cogs_of_sales DECIMAL(24,8) NULL,
  expense_of_sales DECIMAL(24,8) NULL,
  profit_to_gr DECIMAL(24,8) NULL,
  saleexp_to_gr DECIMAL(24,8) NULL,
  adminexp_of_gr DECIMAL(24,8) NULL,
  finaexp_of_gr DECIMAL(24,8) NULL,
  impai_ttm DECIMAL(24,8) NULL,
  gc_of_gr DECIMAL(24,8) NULL,
  op_of_gr DECIMAL(24,8) NULL,
  ebit_of_gr DECIMAL(24,8) NULL,
  roe DECIMAL(24,8) NULL,
  roe_waa DECIMAL(24,8) NULL,
  roe_dt DECIMAL(24,8) NULL,
  roa DECIMAL(24,8) NULL,
  npta DECIMAL(24,8) NULL,
  roic DECIMAL(24,8) NULL,
  roe_yearly DECIMAL(24,8) NULL,
  roa2_yearly DECIMAL(24,8) NULL,
  roe_avg DECIMAL(24,8) NULL,
  opincome_of_ebt DECIMAL(24,8) NULL,
  investincome_of_ebt DECIMAL(24,8) NULL,
  n_op_profit_of_ebt DECIMAL(24,8) NULL,
  tax_to_ebt DECIMAL(24,8) NULL,
  dtprofit_to_profit DECIMAL(24,8) NULL,
  salescash_to_or DECIMAL(24,8) NULL,
  ocf_to_or DECIMAL(24,8) NULL,
  ocf_to_opincome DECIMAL(24,8) NULL,
  capitalized_to_da DECIMAL(24,8) NULL,
  debt_to_assets DECIMAL(24,8) NULL,
  assets_to_eqt DECIMAL(24,8) NULL,
  dp_assets_to_eqt DECIMAL(24,8) NULL,
  ca_to_assets DECIMAL(24,8) NULL,
  nca_to_assets DECIMAL(24,8) NULL,
  tbassets_to_totalassets DECIMAL(24,8) NULL,
  int_to_talcap DECIMAL(24,8) NULL,
  eqt_to_talcapital DECIMAL(24,8) NULL,
  currentdebt_to_debt DECIMAL(24,8) NULL,
  longdeb_to_debt DECIMAL(24,8) NULL,
  ocf_to_shortdebt DECIMAL(24,8) NULL,
  debt_to_eqt DECIMAL(24,8) NULL,
  eqt_to_debt DECIMAL(24,8) NULL,
  eqt_to_interestdebt DECIMAL(24,8) NULL,
  tangibleasset_to_debt DECIMAL(24,8) NULL,
  tangasset_to_intdebt DECIMAL(24,8) NULL,
  tangibleasset_to_netdebt DECIMAL(24,8) NULL,
  ocf_to_debt DECIMAL(24,8) NULL,
  ocf_to_interestdebt DECIMAL(24,8) NULL,
  ocf_to_netdebt DECIMAL(24,8) NULL,
  ebit_to_interest DECIMAL(24,8) NULL,
  longdebt_to_workingcapital DECIMAL(24,8) NULL,
  ebitda_to_debt DECIMAL(24,8) NULL,
  turn_days DECIMAL(24,8) NULL,
  roa_yearly DECIMAL(24,8) NULL,
  roa_dp DECIMAL(24,8) NULL,
  fixed_assets DECIMAL(24,8) NULL,
  profit_prefin_exp DECIMAL(24,8) NULL,
  non_op_profit DECIMAL(24,8) NULL,
  op_to_ebt DECIMAL(24,8) NULL,
  nop_to_ebt DECIMAL(24,8) NULL,
  ocf_to_profit DECIMAL(24,8) NULL,
  cash_to_liqdebt DECIMAL(24,8) NULL,
  cash_to_liqdebt_withinterest DECIMAL(24,8) NULL,
  op_to_liqdebt DECIMAL(24,8) NULL,
  op_to_debt DECIMAL(24,8) NULL,
  roic_yearly DECIMAL(24,8) NULL,
  total_fa_trun DECIMAL(24,8) NULL,
  profit_to_op DECIMAL(24,8) NULL,
  q_opincome DECIMAL(24,8) NULL,
  q_investincome DECIMAL(24,8) NULL,
  q_dtprofit DECIMAL(24,8) NULL,
  q_eps DECIMAL(24,8) NULL,
  q_netprofit_margin DECIMAL(24,8) NULL,
  q_gsprofit_margin DECIMAL(24,8) NULL,
  q_exp_to_sales DECIMAL(24,8) NULL,
  q_profit_to_gr DECIMAL(24,8) NULL,
  q_saleexp_to_gr DECIMAL(24,8) NULL,
  q_adminexp_to_gr DECIMAL(24,8) NULL,
  q_finaexp_to_gr DECIMAL(24,8) NULL,
  q_impair_to_gr_ttm DECIMAL(24,8) NULL,
  q_gc_to_gr DECIMAL(24,8) NULL,
  q_op_to_gr DECIMAL(24,8) NULL,
  q_roe DECIMAL(24,8) NULL,
  q_dt_roe DECIMAL(24,8) NULL,
  q_npta DECIMAL(24,8) NULL,
  q_opincome_to_ebt DECIMAL(24,8) NULL,
  q_investincome_to_ebt DECIMAL(24,8) NULL,
  q_dtprofit_to_profit DECIMAL(24,8) NULL,
  q_salescash_to_or DECIMAL(24,8) NULL,
  q_ocf_to_sales DECIMAL(24,8) NULL,
  q_ocf_to_or DECIMAL(24,8) NULL,
  basic_eps_yoy DECIMAL(24,8) NULL,
  dt_eps_yoy DECIMAL(24,8) NULL,
  cfps_yoy DECIMAL(24,8) NULL,
  op_yoy DECIMAL(24,8) NULL,
  ebt_yoy DECIMAL(24,8) NULL,
  netprofit_yoy DECIMAL(24,8) NULL,
  dt_netprofit_yoy DECIMAL(24,8) NULL,
  ocf_yoy DECIMAL(24,8) NULL,
  roe_yoy DECIMAL(24,8) NULL,
  bps_yoy DECIMAL(24,8) NULL,
  assets_yoy DECIMAL(24,8) NULL,
  eqt_yoy DECIMAL(24,8) NULL,
  tr_yoy DECIMAL(24,8) NULL,
  or_yoy DECIMAL(24,8) NULL,
  q_gr_yoy DECIMAL(24,8) NULL,
  q_gr_qoq DECIMAL(24,8) NULL,
  q_sales_yoy DECIMAL(24,8) NULL,
  q_sales_qoq DECIMAL(24,8) NULL,
  q_op_yoy DECIMAL(24,8) NULL,
  q_op_qoq DECIMAL(24,8) NULL,
  q_profit_yoy DECIMAL(24,8) NULL,
  q_profit_qoq DECIMAL(24,8) NULL,
  q_netprofit_yoy DECIMAL(24,8) NULL,
  q_netprofit_qoq DECIMAL(24,8) NULL,
  equity_yoy DECIMAL(24,8) NULL,
  rd_exp DECIMAL(24,8) NULL,
  update_flag VARCHAR(8) NULL,
  PRIMARY KEY (ts_code, end_date, ann_date),
  KEY idx_fina_indicator_ann_date (ann_date),
  KEY idx_fina_indicator_end_date (end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS income (
  ts_code VARCHAR(16) NOT NULL,
  ann_date CHAR(8) NOT NULL,
  f_ann_date CHAR(8) NULL,
  end_date CHAR(8) NOT NULL,
  report_type VARCHAR(8) NOT NULL,
  comp_type VARCHAR(8) NULL,
  end_type VARCHAR(8) NULL,
  basic_eps DECIMAL(24,8) NULL,
  diluted_eps DECIMAL(24,8) NULL,
  total_revenue DECIMAL(24,4) NULL,
  revenue DECIMAL(24,4) NULL,
  int_income DECIMAL(24,4) NULL,
  prem_earned DECIMAL(24,4) NULL,
  comm_income DECIMAL(24,4) NULL,
  n_commis_income DECIMAL(24,4) NULL,
  n_oth_income DECIMAL(24,4) NULL,
  n_oth_b_income DECIMAL(24,4) NULL,
  prem_income DECIMAL(24,4) NULL,
  out_prem DECIMAL(24,4) NULL,
  une_prem_reser DECIMAL(24,4) NULL,
  reins_income DECIMAL(24,4) NULL,
  n_sec_tb_income DECIMAL(24,4) NULL,
  n_sec_uw_income DECIMAL(24,4) NULL,
  n_asset_mg_income DECIMAL(24,4) NULL,
  oth_b_income DECIMAL(24,4) NULL,
  fv_value_chg_gain DECIMAL(24,4) NULL,
  invest_income DECIMAL(24,4) NULL,
  ass_invest_income DECIMAL(24,4) NULL,
  forex_gain DECIMAL(24,4) NULL,
  total_cogs DECIMAL(24,4) NULL,
  oper_cost DECIMAL(24,4) NULL,
  int_exp DECIMAL(24,4) NULL,
  comm_exp DECIMAL(24,4) NULL,
  biz_tax_surchg DECIMAL(24,4) NULL,
  sell_exp DECIMAL(24,4) NULL,
  admin_exp DECIMAL(24,4) NULL,
  fin_exp DECIMAL(24,4) NULL,
  assets_impair_loss DECIMAL(24,4) NULL,
  prem_refund DECIMAL(24,4) NULL,
  compens_payout DECIMAL(24,4) NULL,
  reser_insur_liab DECIMAL(24,4) NULL,
  div_payt DECIMAL(24,4) NULL,
  reins_exp DECIMAL(24,4) NULL,
  oper_exp DECIMAL(24,4) NULL,
  compens_payout_refu DECIMAL(24,4) NULL,
  insur_reser_refu DECIMAL(24,4) NULL,
  reins_cost_refund DECIMAL(24,4) NULL,
  other_bus_cost DECIMAL(24,4) NULL,
  operate_profit DECIMAL(24,4) NULL,
  non_oper_income DECIMAL(24,4) NULL,
  non_oper_exp DECIMAL(24,4) NULL,
  nca_disploss DECIMAL(24,4) NULL,
  total_profit DECIMAL(24,4) NULL,
  income_tax DECIMAL(24,4) NULL,
  n_income DECIMAL(24,4) NULL,
  n_income_attr_p DECIMAL(24,4) NULL,
  minority_gain DECIMAL(24,4) NULL,
  oth_compr_income DECIMAL(24,4) NULL,
  t_compr_income DECIMAL(24,4) NULL,
  compr_inc_attr_p DECIMAL(24,4) NULL,
  compr_inc_attr_m_s DECIMAL(24,4) NULL,
  ebit DECIMAL(24,4) NULL,
  ebitda DECIMAL(24,4) NULL,
  insurance_exp DECIMAL(24,4) NULL,
  undist_profit DECIMAL(24,4) NULL,
  distable_profit DECIMAL(24,4) NULL,
  update_flag VARCHAR(8) NULL,
  PRIMARY KEY (ts_code, end_date, ann_date, report_type),
  KEY idx_income_ann_date (ann_date),
  KEY idx_income_end_date (end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS balancesheet (
  ts_code VARCHAR(16) NOT NULL,
  ann_date CHAR(8) NOT NULL,
  f_ann_date CHAR(8) NULL,
  end_date CHAR(8) NOT NULL,
  report_type VARCHAR(8) NOT NULL,
  comp_type VARCHAR(8) NULL,
  end_type VARCHAR(8) NULL,
  total_share DECIMAL(24,4) NULL,
  cap_rese DECIMAL(24,4) NULL,
  undistr_porfit DECIMAL(24,4) NULL,
  surplus_rese DECIMAL(24,4) NULL,
  special_rese DECIMAL(24,4) NULL,
  money_cap DECIMAL(24,4) NULL,
  trad_asset DECIMAL(24,4) NULL,
  notes_receiv DECIMAL(24,4) NULL,
  accounts_receiv DECIMAL(24,4) NULL,
  oth_receiv DECIMAL(24,4) NULL,
  prepayment DECIMAL(24,4) NULL,
  div_receiv DECIMAL(24,4) NULL,
  int_receiv DECIMAL(24,4) NULL,
  inventories DECIMAL(24,4) NULL,
  amor_exp DECIMAL(24,4) NULL,
  nca_within_1y DECIMAL(24,4) NULL,
  sett_rsrv DECIMAL(24,4) NULL,
  loanto_oth_bank_fi DECIMAL(24,4) NULL,
  premium_receiv DECIMAL(24,4) NULL,
  reinsur_receiv DECIMAL(24,4) NULL,
  reinsur_res_receiv DECIMAL(24,4) NULL,
  pur_resale_fa DECIMAL(24,4) NULL,
  oth_cur_assets DECIMAL(24,4) NULL,
  total_cur_assets DECIMAL(24,4) NULL,
  fa_avail_for_sale DECIMAL(24,4) NULL,
  htm_invest DECIMAL(24,4) NULL,
  lt_eqt_invest DECIMAL(24,4) NULL,
  invest_real_estate DECIMAL(24,4) NULL,
  time_deposits DECIMAL(24,4) NULL,
  oth_assets DECIMAL(24,4) NULL,
  lt_rec DECIMAL(24,4) NULL,
  fix_assets DECIMAL(24,4) NULL,
  cip DECIMAL(24,4) NULL,
  const_materials DECIMAL(24,4) NULL,
  fixed_assets_disp DECIMAL(24,4) NULL,
  produc_bio_assets DECIMAL(24,4) NULL,
  oil_and_gas_assets DECIMAL(24,4) NULL,
  intan_assets DECIMAL(24,4) NULL,
  r_and_d DECIMAL(24,4) NULL,
  goodwill DECIMAL(24,4) NULL,
  lt_amor_exp DECIMAL(24,4) NULL,
  defer_tax_assets DECIMAL(24,4) NULL,
  decr_in_disbur DECIMAL(24,4) NULL,
  oth_nca DECIMAL(24,4) NULL,
  total_nca DECIMAL(24,4) NULL,
  cash_reser_cb DECIMAL(24,4) NULL,
  depos_in_oth_bfi DECIMAL(24,4) NULL,
  prec_metals DECIMAL(24,4) NULL,
  deriv_assets DECIMAL(24,4) NULL,
  rr_reins_une_prem DECIMAL(24,4) NULL,
  rr_reins_outstd_cla DECIMAL(24,4) NULL,
  rr_reins_lins_liab DECIMAL(24,4) NULL,
  rr_reins_lthins_liab DECIMAL(24,4) NULL,
  refund_depos DECIMAL(24,4) NULL,
  ph_pledge_loans DECIMAL(24,4) NULL,
  refund_cap_depos DECIMAL(24,4) NULL,
  indep_acct_assets DECIMAL(24,4) NULL,
  client_depos DECIMAL(24,4) NULL,
  client_prov DECIMAL(24,4) NULL,
  transac_seat_fee DECIMAL(24,4) NULL,
  invest_as_receiv DECIMAL(24,4) NULL,
  total_assets DECIMAL(24,4) NULL,
  lt_borr DECIMAL(24,4) NULL,
  st_borr DECIMAL(24,4) NULL,
  cb_borr DECIMAL(24,4) NULL,
  depos_ib_deposits DECIMAL(24,4) NULL,
  loan_oth_bank DECIMAL(24,4) NULL,
  trading_fl DECIMAL(24,4) NULL,
  notes_payable DECIMAL(24,4) NULL,
  acct_payable DECIMAL(24,4) NULL,
  adv_receipts DECIMAL(24,4) NULL,
  sold_for_repur_fa DECIMAL(24,4) NULL,
  comm_payable DECIMAL(24,4) NULL,
  payroll_payable DECIMAL(24,4) NULL,
  taxes_payable DECIMAL(24,4) NULL,
  int_payable DECIMAL(24,4) NULL,
  div_payable DECIMAL(24,4) NULL,
  oth_payable DECIMAL(24,4) NULL,
  acc_exp DECIMAL(24,4) NULL,
  deferred_inc DECIMAL(24,4) NULL,
  st_bonds_payable DECIMAL(24,4) NULL,
  payable_to_reinsurer DECIMAL(24,4) NULL,
  rsrv_insur_cont DECIMAL(24,4) NULL,
  acting_trading_sec DECIMAL(24,4) NULL,
  acting_uw_sec DECIMAL(24,4) NULL,
  non_cur_liab_due_1y DECIMAL(24,4) NULL,
  oth_cur_liab DECIMAL(24,4) NULL,
  total_cur_liab DECIMAL(24,4) NULL,
  bond_payable DECIMAL(24,4) NULL,
  lt_payable DECIMAL(24,4) NULL,
  specific_payables DECIMAL(24,4) NULL,
  estimated_liab DECIMAL(24,4) NULL,
  defer_tax_liab DECIMAL(24,4) NULL,
  defer_inc_non_cur_liab DECIMAL(24,4) NULL,
  oth_ncl DECIMAL(24,4) NULL,
  total_ncl DECIMAL(24,4) NULL,
  depos_oth_bfi DECIMAL(24,4) NULL,
  deriv_liab DECIMAL(24,4) NULL,
  depos DECIMAL(24,4) NULL,
  agency_bus_liab DECIMAL(24,4) NULL,
  oth_liab DECIMAL(24,4) NULL,
  prem_receiv_adva DECIMAL(24,4) NULL,
  depos_received DECIMAL(24,4) NULL,
  ph_invest DECIMAL(24,4) NULL,
  reser_une_prem DECIMAL(24,4) NULL,
  reser_outstd_claims DECIMAL(24,4) NULL,
  reser_lins_liab DECIMAL(24,4) NULL,
  reser_lthins_liab DECIMAL(24,4) NULL,
  indept_acc_liab DECIMAL(24,4) NULL,
  pledge_borr DECIMAL(24,4) NULL,
  indem_payable DECIMAL(24,4) NULL,
  policy_div_payable DECIMAL(24,4) NULL,
  total_liab DECIMAL(24,4) NULL,
  treasury_share DECIMAL(24,4) NULL,
  ordin_risk_reser DECIMAL(24,4) NULL,
  forex_differ DECIMAL(24,4) NULL,
  invest_loss_unconf DECIMAL(24,4) NULL,
  minority_int DECIMAL(24,4) NULL,
  total_hldr_eqy_exc_min_int DECIMAL(24,4) NULL,
  total_hldr_eqy_inc_min_int DECIMAL(24,4) NULL,
  total_liab_hldr_eqy DECIMAL(24,4) NULL,
  lt_payroll_payable DECIMAL(24,4) NULL,
  oth_comp_income DECIMAL(24,4) NULL,
  oth_eqt_tools DECIMAL(24,4) NULL,
  oth_eqt_tools_p_shr DECIMAL(24,4) NULL,
  lending_funds DECIMAL(24,4) NULL,
  acc_receivable DECIMAL(24,4) NULL,
  st_fin_payable DECIMAL(24,4) NULL,
  payables DECIMAL(24,4) NULL,
  hfs_assets DECIMAL(24,4) NULL,
  hfs_sales DECIMAL(24,4) NULL,
  cost_fin_assets DECIMAL(24,4) NULL,
  fair_value_fin_assets DECIMAL(24,4) NULL,
  cip_total DECIMAL(24,4) NULL,
  oth_pay_total DECIMAL(24,4) NULL,
  long_pay_total DECIMAL(24,4) NULL,
  debt_invest DECIMAL(24,4) NULL,
  oth_debt_invest DECIMAL(24,4) NULL,
  oth_eq_invest DECIMAL(24,4) NULL,
  oth_illiq_fin_assets DECIMAL(24,4) NULL,
  oth_eq_ppbond DECIMAL(24,4) NULL,
  receiv_financing DECIMAL(24,4) NULL,
  use_right_assets DECIMAL(24,4) NULL,
  lease_liab DECIMAL(24,4) NULL,
  contract_assets DECIMAL(24,4) NULL,
  contract_liab DECIMAL(24,4) NULL,
  accounts_receiv_bill DECIMAL(24,4) NULL,
  accounts_pay DECIMAL(24,4) NULL,
  oth_rcv_total DECIMAL(24,4) NULL,
  fix_assets_total DECIMAL(24,4) NULL,
  update_flag VARCHAR(8) NULL,
  PRIMARY KEY (ts_code, end_date, ann_date, report_type),
  KEY idx_balancesheet_ann_date (ann_date),
  KEY idx_balancesheet_end_date (end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cashflow (
  ts_code VARCHAR(16) NOT NULL,
  ann_date CHAR(8) NOT NULL,
  f_ann_date CHAR(8) NULL,
  end_date CHAR(8) NOT NULL,
  comp_type VARCHAR(8) NULL,
  report_type VARCHAR(8) NOT NULL,
  end_type VARCHAR(8) NULL,
  net_profit DECIMAL(24,4) NULL,
  finan_exp DECIMAL(24,4) NULL,
  c_fr_sale_sg DECIMAL(24,4) NULL,
  recp_tax_rends DECIMAL(24,4) NULL,
  n_depos_incr_fi DECIMAL(24,4) NULL,
  n_incr_loans_cb DECIMAL(24,4) NULL,
  n_inc_borr_oth_fi DECIMAL(24,4) NULL,
  prem_fr_orig_contr DECIMAL(24,4) NULL,
  n_incr_insured_dep DECIMAL(24,4) NULL,
  n_reinsur_prem DECIMAL(24,4) NULL,
  n_incr_disp_tfa DECIMAL(24,4) NULL,
  ifc_cash_incr DECIMAL(24,4) NULL,
  n_incr_disp_faas DECIMAL(24,4) NULL,
  n_incr_loans_oth_bank DECIMAL(24,4) NULL,
  n_cap_incr_repur DECIMAL(24,4) NULL,
  c_fr_oth_operate_a DECIMAL(24,4) NULL,
  c_inf_fr_operate_a DECIMAL(24,4) NULL,
  c_paid_goods_s DECIMAL(24,4) NULL,
  c_paid_to_for_empl DECIMAL(24,4) NULL,
  c_paid_for_taxes DECIMAL(24,4) NULL,
  n_incr_clt_loan_adv DECIMAL(24,4) NULL,
  n_incr_dep_cbob DECIMAL(24,4) NULL,
  c_pay_claims_orig_inco DECIMAL(24,4) NULL,
  pay_handling_chrg DECIMAL(24,4) NULL,
  pay_comm_insur_plcy DECIMAL(24,4) NULL,
  oth_cash_pay_oper_act DECIMAL(24,4) NULL,
  st_cash_out_act DECIMAL(24,4) NULL,
  n_cashflow_act DECIMAL(24,4) NULL,
  oth_recp_ral_inv_act DECIMAL(24,4) NULL,
  c_disp_withdrwl_invest DECIMAL(24,4) NULL,
  c_recp_return_invest DECIMAL(24,4) NULL,
  n_recp_disp_fiolta DECIMAL(24,4) NULL,
  n_recp_disp_sobu DECIMAL(24,4) NULL,
  stot_inflows_inv_act DECIMAL(24,4) NULL,
  c_pay_acq_const_fiolta DECIMAL(24,4) NULL,
  c_paid_invest DECIMAL(24,4) NULL,
  n_disp_subs_oth_biz DECIMAL(24,4) NULL,
  oth_pay_ral_inv_act DECIMAL(24,4) NULL,
  n_incr_pledge_loan DECIMAL(24,4) NULL,
  stot_out_inv_act DECIMAL(24,4) NULL,
  n_cashflow_inv_act DECIMAL(24,4) NULL,
  c_recp_borrow DECIMAL(24,4) NULL,
  proc_issue_bonds DECIMAL(24,4) NULL,
  oth_cash_recp_ral_fnc_act DECIMAL(24,4) NULL,
  stot_cash_in_fnc_act DECIMAL(24,4) NULL,
  free_cashflow DECIMAL(24,4) NULL,
  c_prepay_amt_borr DECIMAL(24,4) NULL,
  c_pay_dist_dpcp_int_exp DECIMAL(24,4) NULL,
  incl_dvd_profit_paid_sc_ms DECIMAL(24,4) NULL,
  oth_cashpay_ral_fnc_act DECIMAL(24,4) NULL,
  stot_cashout_fnc_act DECIMAL(24,4) NULL,
  n_cash_flows_fnc_act DECIMAL(24,4) NULL,
  eff_fx_flu_cash DECIMAL(24,4) NULL,
  n_incr_cash_cash_equ DECIMAL(24,4) NULL,
  c_cash_equ_beg_period DECIMAL(24,4) NULL,
  c_cash_equ_end_period DECIMAL(24,4) NULL,
  c_recp_cap_contrib DECIMAL(24,4) NULL,
  incl_cash_rec_saims DECIMAL(24,4) NULL,
  uncon_invest_loss DECIMAL(24,4) NULL,
  prov_depr_assets DECIMAL(24,4) NULL,
  depr_fa_coga_dpba DECIMAL(24,4) NULL,
  amort_intang_assets DECIMAL(24,4) NULL,
  lt_amort_deferred_exp DECIMAL(24,4) NULL,
  decr_deferred_exp DECIMAL(24,4) NULL,
  incr_acc_exp DECIMAL(24,4) NULL,
  loss_disp_fiolta DECIMAL(24,4) NULL,
  loss_scr_fa DECIMAL(24,4) NULL,
  loss_fv_chg DECIMAL(24,4) NULL,
  invest_loss DECIMAL(24,4) NULL,
  decr_def_inc_tax_assets DECIMAL(24,4) NULL,
  incr_def_inc_tax_liab DECIMAL(24,4) NULL,
  decr_inventories DECIMAL(24,4) NULL,
  decr_oper_payable DECIMAL(24,4) NULL,
  incr_oper_payable DECIMAL(24,4) NULL,
  others DECIMAL(24,4) NULL,
  im_net_cashflow_oper_act DECIMAL(24,4) NULL,
  conv_debt_into_cap DECIMAL(24,4) NULL,
  conv_copbonds_due_within_1y DECIMAL(24,4) NULL,
  fa_fnc_leases DECIMAL(24,4) NULL,
  im_n_incr_cash_equ DECIMAL(24,4) NULL,
  net_dism_capital_add DECIMAL(24,4) NULL,
  net_cash_rece_sec DECIMAL(24,4) NULL,
  credit_impa_loss DECIMAL(24,4) NULL,
  use_right_asset_dep DECIMAL(24,4) NULL,
  oth_loss_asset DECIMAL(24,4) NULL,
  end_bal_cash DECIMAL(24,4) NULL,
  beg_bal_cash DECIMAL(24,4) NULL,
  end_bal_cash_equ DECIMAL(24,4) NULL,
  beg_bal_cash_equ DECIMAL(24,4) NULL,
  update_flag VARCHAR(8) NULL,
  PRIMARY KEY (ts_code, end_date, ann_date, report_type),
  KEY idx_cashflow_ann_date (ann_date),
  KEY idx_cashflow_end_date (end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
